# Generated by Django 6.0 on 2026-01-05 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pediatric", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicinePrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=200)),
                (
                    "dosage",
                    models.CharField(help_text="e.g., 500mg, 10ml", max_length=100),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Once Daily", "Once Daily"),
                            ("Twice Daily", "Twice Daily"),
                            ("Thrice Daily", "Thrice Daily"),
                            ("Four Times Daily", "Four Times Daily"),
                            ("Every 6 Hours", "Every 6 Hours"),
                            ("Every 8 Hours", "Every 8 Hours"),
                            ("Every 12 Hours", "Every 12 Hours"),
                            ("As Needed", "As Needed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "duration_value",
                    models.IntegerField(help_text="Number of days/weeks/months"),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("Days", "Days"),
                            ("Weeks", "Weeks"),
                            ("Months", "Months"),
                        ],
                        default="Days",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "indication",
                    models.TextField(
                        blank=True, help_text="Why this medicine is prescribed"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions (e.g., take with food)",
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Known side effects"),
                ),
                (
                    "prescribed_by",
                    models.CharField(
                        blank=True, help_text="Doctor's name", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("Discontinued", "Discontinued"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="pediatric.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Report", "Medical Report"),
                            ("Test", "Lab Test"),
                            ("Image", "X-Ray/Ultrasound"),
                            ("Prescription", "Prescription"),
                            ("Vaccination", "Vaccination Certificate"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="patient_documents/%Y/%m/%d/")),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="pediatric.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_date"],
            },
        ),
    ]
