# Generated by Django 6.0 on 2026-01-04 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthPercentile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_in_months",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(240),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[("Height", "Height"), ("Weight", "Weight")],
                        max_length=30,
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[("WHO", "WHO (0-24m)"), ("CDC", "CDC (2-18y)")],
                        max_length=20,
                    ),
                ),
                ("percentile_2nd", models.FloatField()),
                ("percentile_5th", models.FloatField()),
                ("percentile_10th", models.FloatField()),
                ("percentile_25th", models.FloatField()),
                ("percentile_50th", models.FloatField()),
                ("percentile_75th", models.FloatField()),
                ("percentile_90th", models.FloatField()),
                ("percentile_95th", models.FloatField()),
                ("percentile_98th", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["age_in_months", "gender", "chart_type"],
                "unique_together": {
                    ("age_in_months", "gender", "chart_type", "standard")
                },
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_datetime", models.DateTimeField(auto_now_add=True)),
                ("logout_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Success", "Successful Login"),
                            ("Failed", "Failed Login"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-login_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "parent_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("medical_history", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_registered", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_registered"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_date", models.DateField()),
                (
                    "height",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(250),
                        ]
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                ("head_circumference", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("recorded_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="pediatric.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-measurement_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("Admin", "Administrator"),
                            ("Staff", "Medical Staff"),
                        ],
                        default="Staff",
                        max_length=20,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
